# Generated by Django 3.1.4 on 2021-01-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text_slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
