# Generated by Django 3.1.4 on 2021-01-12 16:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_text_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='Collects user ids as Integer', size=None),
        ),
    ]
